import os
import datetime
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

def main():
    """
    Create a daily update file and print a timestamp
    """
    # Get current date and time
    now = datetime.datetime.now()
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")
    
    # Create a directory for daily updates if it doesn't exist
    updates_dir = "daily_updates"
    if not os.path.exists(updates_dir):
        os.makedirs(updates_dir)
    
    # Create a new file with the current timestamp
    filename = f"{updates_dir}/update_{now.strftime('%Y_%m_%d')}.txt"
    
    # Write content to the file
    with open(filename, "w") as f:
        f.write(f"Daily update created at: {timestamp}\n")
        f.write(f"This file was automatically generated by GitHub Actions.\n")
        
        # Add some environment variables (safely)
        user = os.getenv("GITHUB_ACTOR", "Unknown")
        repo = os.getenv("GITHUB_REPOSITORY", "Unknown")
        
        f.write(f"Repository: {repo}\n")
        f.write(f"Generated by: {user}\n")
    
    print(f"Created daily update file: {filename}")
    print(f"Timestamp: {timestamp}")

if __name__ == "__main__":
    main()
