name: Daily Commit

on:
  schedule:
    # Run at 15:45 UTC every day (specific time as required)
    - cron: '45 15 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
      
      - name: Create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          echo "CUSTOM_VAR=example_value" >> .env
      
      - name: Generate daily update by 24f2006438@ds.study.iitm.ac.in
        run: python eight.py
      
      - name: Configure Git
        run: |
          git config --local user.email "24f2006438@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Actions"
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Daily automated update $(date +%Y-%m-%d)"
          git push
